networks:
  docker-practice-net:

volumes:
  postgres-data:
    driver: local
  postgres-dump:
    driver: local

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5443:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: school
      POSTGRES_DB: school
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
      - ../../data/dump:/db-dump
    networks:
      - docker-practice-net

  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - docker-practice-net

  app:
    build:
      context: ../..                      # Путь из ops-tools/docker в корень проекта
      dockerfile: ops-tools/images/app/Dockerfile  # Относительно контекста
    container_name: app_container
    ports:
      - "8888:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/school
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: school
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - docker-practice-net
